# Generated by Django 4.1.3 on 2022-12-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptorRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptor1', models.CharField(choices=[('HSV', 'Hsv'), ('BGR', 'Bgr'), ('SIFT', 'Sift'), ('ORB', 'Orb'), ('GLCM', 'Glcm'), ('LBP', 'Lbp'), ('HOG', 'Hog'), ('VGG16', 'Vgg16'), ('VGG16_1', 'Vgg16 1')], default='BGR', max_length=15)),
                ('descriptor2', models.CharField(blank=True, choices=[('HSV', 'Hsv'), ('BGR', 'Bgr'), ('SIFT', 'Sift'), ('ORB', 'Orb'), ('GLCM', 'Glcm'), ('LBP', 'Lbp'), ('HOG', 'Hog'), ('VGG16', 'Vgg16'), ('VGG16_1', 'Vgg16 1')], default='BGR', max_length=15)),
                ('distance', models.CharField(choices=[('Euclidean', 'Euclidean'), ('Chi Square', 'Chi Square'), ('Bhattacharya', 'Bhattacharya'), ('Flann', 'Flann'), ('Brute Force', 'Brute Force'), ('Intersection', 'Intersection'), ('Correlation', 'Correlation')], default='Euclidean', max_length=15)),
                ('top', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='ImageRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('classification', models.IntegerField(choices=[(0, 'Araignee'), (1, 'Chien'), (2, 'Oiseau'), (3, 'Poisson'), (4, 'Singe')], default=0)),
                ('is_database_img', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='images/requests')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
