# Generated by Django 4.1.3 on 2022-12-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIR', '0004_alter_descriptorrequests_descriptor1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptorrequests',
            name='top',
            field=models.IntegerField(choices=[(5, 'Top 5'), (10, 'Top 10'), (20, 'Top 20'), (50, 'Top 50'), (100, 'Top 100'), (200, 'Top 200'), (0, 'Top Max')], default=5),
        ),
    ]
