# Generated by Django 4.1.3 on 2022-12-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIR', '0007_alter_descriptorrequests_descriptor1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptorrequests',
            name='descriptor1',
            field=models.CharField(choices=[('BGR', 'Bgr'), ('HSV', 'Hsv'), ('SIFT', 'Sift'), ('ORB', 'Orb'), ('GLCM', 'Glcm'), ('LBP', 'Lbp'), ('HOG', 'Hog'), ('VGG16', 'Vgg16'), ('VGG16_1', 'Vgg16 1'), ('RESNET101', 'Resnet101'), ('RESNET101_1', 'Resnet101 1'), ('RESNET50', 'Resnet50'), ('RESNET50_1', 'Resnet50 1'), ('MOBILENET', 'Mobilenet')], default='BGR', max_length=15),
        ),
        migrations.AlterField(
            model_name='descriptorrequests',
            name='descriptor2',
            field=models.CharField(blank=True, choices=[('BGR', 'Bgr'), ('HSV', 'Hsv'), ('SIFT', 'Sift'), ('ORB', 'Orb'), ('GLCM', 'Glcm'), ('LBP', 'Lbp'), ('HOG', 'Hog'), ('VGG16', 'Vgg16'), ('VGG16_1', 'Vgg16 1'), ('RESNET101', 'Resnet101'), ('RESNET101_1', 'Resnet101 1'), ('RESNET50', 'Resnet50'), ('RESNET50_1', 'Resnet50 1'), ('MOBILENET', 'Mobilenet')], max_length=15),
        ),
    ]
