# Generated by Django 4.1.3 on 2022-12-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIR', '0009_alter_descriptorrequests_descriptor1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptorrequests',
            name='R_precision',
            field=models.IntegerField(default=10),
        ),
    ]
