# Generated by Django 4.1.3 on 2023-01-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIR', '0010_descriptorrequests_r_precision'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerequests',
            name='subclassification',
            field=models.IntegerField(choices=[(0, 'Barn Spider'), (1, 'Wolf Spider'), (2, 'Trap Door Spider'), (3, 'Orb Weaving Spider'), (4, 'Garden Spider'), (5, 'Tarentula'), (10, 'Siberian Husky'), (11, 'Labrador Retriever'), (12, 'Boxer'), (13, 'Chihuahua'), (14, 'Golden Retriever'), (15, 'Rottweiler'), (20, 'Vulture'), (21, 'Parrot'), (22, 'Great Grey Owl'), (23, 'Blue Jay'), (24, 'Robin'), (25, 'Bulbul'), (30, 'Dog Fish'), (31, 'Ray'), (32, 'Guitarfish'), (33, 'Tiger Shark'), (34, 'Eagle Ray'), (35, 'Hammerhead'), (45, 'Baboon'), (41, 'Chimpanzee'), (42, 'Gorilla'), (40, 'Macaque'), (44, 'Oranguton'), (43, 'Squirrel Monkey')], default=0),
        ),
    ]
