version: "3.1"

volumes:
  db-data:

services:

  django:
    build: .
    container_name: ${PROJECT_NAME}
    restart: unless-stopped
    command: bash -c "
      python3 manage.py makemigrations
      && python3 manage.py migrate
      && python3 manage.py loaddata features/features.json
      && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../app/:/app
    ports:
      - "8000:8000"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: ${PROJECT_NAME}-mysql
    working_dir: /application
    restart: unless-stopped
    volumes:
      - db-data:/application
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_USER}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "8306:3306"