name: auto Deploy
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: '${{ secrets.DOCKER_USERNAME }}'
          password: '${{ secrets.DOCKER_PASSWORD }}'
      - name: 'Extract metadata (tags, labels) for Docker'
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: '${{ secrets.DOCKER_USERNAME }}/Projet_MIR_Cloud'
          tags: |
            type=raw,value=c-{{sha}}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: '${{ steps.meta.outputs.tags }}'
          labels: '${{ steps.meta.outputs.labels }}'
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: '${{ secrets.SSH_HOST }}'
          username: '${{ secrets.SSH_USERNAME }}'
          password: '${{ secrets.SSH_PASSWORD }}'
          script: docker run -d -p 8069:8000 ${{ secrets.DOCKER_USERNAME }}/Projet_MIR_Cloud
